---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version

script:
  # Basic setup.yml run
  - make run
